name: Liwarayear4green
favicon: null
layout_spectrum: 0.58958
typography_spectrum: 0.6119
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#3d4d73'
    - '#964b04'
    - '#b9947e'
    - '#d5c3a5'
  brandStrength: 0.5
  lightness: 0.2460673013702035
  saturation: 0.5643851843196899
  rhythmicContrast: 0.7819586803670973
purpose: []
