name: Liwarayear4green
favicon: null
layout_spectrum: 0.6099135654512793
typography_spectrum: 0.8083329135552049
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.16101879929192364
  lightness: 0.2460673013702035
  saturation: 0.5643851843196899
  rhythmicContrast: 0.7819586803670973
purpose: []
