name: Liwarayear4green
favicon: null
layout_spectrum: 0.94182
typography_spectrum: 0.11591
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#254026'
    - '#fa0006'
    - '#599562'
    - '#a1cdac'
  brandStrength: 0.375
  lightness: 0.2460673013702035
  saturation: 0.5643851843196899
  rhythmicContrast: 0.7819586803670973
purpose: []
